from __future__ import annotations

import os
from Crypto.PublicKey import ECC
from dataclasses import dataclass

DEFAULT_NONCE_LEN_BYTES = 12

@dataclass(frozen=True)
class EcdsaKeypair:
    private_pem: str
    public_pem: str
    public_bin: bytes
    public_header_c: str


def render_ecdsa_public_header(public_bin: bytes) -> str:
    lines = ["// Generated by `keygen.py` - DO NOT edit", ""]
    lines.append(f"static const uint8_t gEcdsaPublicKey[{len(public_bin)}] = {{")
    row = "    "
    for i, b in enumerate(public_bin):
        row += f"0x{b:02X}U, "
        if 0 == (i + 1) % 8:
            lines.append(row.rstrip())
            row = "    "
    if row.strip():
        lines.append(row.rstrip())
    lines.append("};")
    return "\n".join(lines) + "\n"


def generate_ecdsa_keypair() -> EcdsaKeypair:
    key = ECC.generate(curve="p256")

    private_pem = key.export_key(format="PEM")
    public_pem = key.public_key().export_key(format="PEM")

    x = int(key.pointQ.x).to_bytes(32, "big")
    y = int(key.pointQ.y).to_bytes(32, "big")
    public_bin = b"\x04" + x + y
    if len(public_bin) != 65:
        raise RuntimeError(f"unexpected public key length {len(public_bin)}")

    public_header_c = render_ecdsa_public_header(public_bin)

    return EcdsaKeypair(
        private_pem=private_pem,
        public_pem=public_pem,
        public_bin=public_bin,
        public_header_c=public_header_c,
    )

@dataclass(frozen=True)
class AesKeyMaterial:
    key: bytes
    nonce: bytes
    key_size_bits: int

def generate_aes_key(key_size_bits: int = 256, nonce_len_bytes: int = DEFAULT_NONCE_LEN_BYTES) -> AesKeyMaterial:
    if key_size_bits not in (128, 192, 256):
        raise ValueError(
            f"Unsupported AES key size {key_size_bits}; "
            f"expected one of {(128, 192, 256)}"
        )

    key = os.urandom(key_size_bits // 8)
    nonce = os.urandom(nonce_len_bytes)

    return AesKeyMaterial(key=key, nonce=nonce, key_size_bits=key_size_bits)
